FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_REPORT_HTTP_URL=/api/report
ARG VITE_REPORT_HTTP_API_KEY=
ARG VITE_SPECIAL_BOT_APP_KEY=
ARG VITE_SPECIAL_WORKFLOW_DEBUG=true
ARG VITE_SPECIAL_AUTO_APPEND_REPLY=false
ARG VITE_CLASSROOM_BOT_APP_KEY=
ARG VITE_CLASSROOM_WORKFLOW_DEBUG=true
ARG VITE_DOC_BOT_APP_KEY=
ARG VITE_DOC_STORAGE_CREDENTIAL_URL=/api/describe-storage-credential
ARG VITE_DOC_COS_UPLOAD_PROXY_URL=/api/cos-upload

ENV VITE_REPORT_HTTP_URL=$VITE_REPORT_HTTP_URL
ENV VITE_REPORT_HTTP_API_KEY=$VITE_REPORT_HTTP_API_KEY
ENV VITE_SPECIAL_BOT_APP_KEY=$VITE_SPECIAL_BOT_APP_KEY
ENV VITE_SPECIAL_WORKFLOW_DEBUG=$VITE_SPECIAL_WORKFLOW_DEBUG
ENV VITE_SPECIAL_AUTO_APPEND_REPLY=$VITE_SPECIAL_AUTO_APPEND_REPLY
ENV VITE_CLASSROOM_BOT_APP_KEY=$VITE_CLASSROOM_BOT_APP_KEY
ENV VITE_CLASSROOM_WORKFLOW_DEBUG=$VITE_CLASSROOM_WORKFLOW_DEBUG
ENV VITE_DOC_BOT_APP_KEY=$VITE_DOC_BOT_APP_KEY
ENV VITE_DOC_STORAGE_CREDENTIAL_URL=$VITE_DOC_STORAGE_CREDENTIAL_URL
ENV VITE_DOC_COS_UPLOAD_PROXY_URL=$VITE_DOC_COS_UPLOAD_PROXY_URL

RUN npm run build

FROM node:22-alpine AS runtime

WORKDIR /app
ENV NODE_ENV=production
ENV PORT=4173

COPY package*.json ./
RUN npm ci && npm cache clean --force

COPY --from=build /app/dist ./dist
COPY --from=build /app/vite.config.js ./vite.config.js

EXPOSE 4173
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "4173"]
